In [1]:
import numpy as np

In [2]:
from buq.data.md import AlanineDipeptideMD
target_function = AlanineDipeptideMD(mode='debug')

/Users/renau001/Documents/projects/quantum/QuantumBayesianQuadrature/buq/.venv/lib/python3.11/site-packages/e3nn/o3/_wigner.py:10: UserWarning: Environment variable TORCH_FORCE_NO_WEIGHTS_ONLY_LOAD detected, since the`weights_only` argument was not explicitly passed to `torch.load`, forcing weights_only=False.
  _Jd, _W3j_flat, _W3j_indices = torch.load(os.path.join(os.path.dirname(__file__), 'constants.pt'))


cuequivariance or cuequivariance_torch is not available. Cuequivariance acceleration will be disabled.


In [3]:
from buq.kernels.rbf import RBFKernel

In [4]:
rbf = RBFKernel(lengthscale=0.75, noise=0.0)

In [5]:
x_data = target_function.generate_samples(10)
y_data = target_function(x_data)
print(x_data)
print(y_data)

Debug mode: Simulating MD run for phi=-1.5222660169129778, psi=-2.4199308244517566
Debug mode: Simulating MD run for phi=-0.8461602685035188, psi=1.5814506793324892
Debug mode: Simulating MD run for phi=0.8146045773765689, psi=-3.045436038648847
Debug mode: Simulating MD run for phi=0.7914188605185348, psi=0.7923853980098094
Debug mode: Simulating MD run for phi=1.027547422864174, psi=-2.54975702909509
Debug mode: Simulating MD run for phi=0.9269241778677735, psi=-2.9616975827948298
Debug mode: Simulating MD run for phi=-3.109774220304692, psi=3.035065076732934
Debug mode: Simulating MD run for phi=-2.6709274885444096, psi=2.35601642523814
Debug mode: Simulating MD run for phi=3.1407329830583377, psi=1.723807276961776
Debug mode: Simulating MD run for phi=-3.01463906081062, psi=-2.7441166477272754
[[-1.52226602 -2.41993082]
 [-0.84616027  1.58145068]
 [ 0.81460458 -3.04543604]
 [ 0.79141886  0.7923854 ]
 [ 1.02754742 -2.54975703]
 [ 0.92692418 -2.96169758]
 [-3.10977422  3.03506508]
 [

In [6]:
bounds = target_function.parameter_space.get_bounds()
# bounds = [d[0] for d in bounds], [d[1] for d in bounds]
print(bounds)

[(-3.141592653589793, 3.141592653589793), (-3.141592653589793, 3.141592653589793)]


In [7]:
rbf.get_kernel(x_data, y_data, bounds=bounds)

 /Users/renau001/Documents/projects/quantum/QuantumBayesianQuadrature/buq/.venv/lib/python3.11/site-packages/paramz/transformations.py:111: RuntimeWarning:divide by zero encountered in log


In [8]:
from buq.buq import ClassicalBayesianQuadratureMD

In [9]:
bq = ClassicalBayesianQuadratureMD(rbf, target_function)

RUNNING THE L-BFGS-B CODE

           * * *

Machine precision = 2.220D-16
 N =          100     M =           10

At X0         0 variables are exactly at the bounds

At iterate    0    f=  3.52110D+01    |proj g|=  6.34787D-01

At iterate   10    f=  6.85924D+00    |proj g|=  7.48246D-03


 This problem is unconstrained.



At iterate   20    f=  6.81393D+00    |proj g|=  5.84155D-04

At iterate   30    f=  6.81386D+00    |proj g|=  5.11591D-05
Debug mode: Simulating MD run for phi=-0.9096185941523309, psi=0.8145370260901426

           * * *

Tit   = total number of iterations
Tnf   = total number of function evaluations
Tnint = total number of segments explored during Cauchy searches
Skip  = number of BFGS updates skipped
Nact  = number of active bounds at final generalized Cauchy point
Projg = norm of the final projected gradient
F     = final function value

           * * *

   N    Tit     Tnf  Tnint  Skip  Nact     Projg        F
  100     32     36      1     0     0   6.661D-06   6.814D+00
  F =   6.8138587468487257     

CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL            
Debug mode: Simulating MD run for phi=1.5890128519279516, psi=2.043396373370201


In [ ]:
bq.run(10, plot_fit=True)

 -------------- BaysOpt loop, query 0 ---------------
[[-8.39402547e-08 -1.22532866e-08]
 [-8.68724481e-07 -1.26813173e-07]
 [-3.78000051e-06 -5.51790437e-07]
 [-6.91511901e-06 -1.00944362e-06]
 [-5.31869495e-06 -7.76407443e-07]
 [-1.71988606e-06 -2.51092132e-07]
 [-2.33719846e-07 -3.42068474e-08]
 [-1.32188284e-08 -2.04306059e-09]
 [-2.42466353e-10 -9.59704938e-11]
 [ 1.44386185e-11 -1.14939728e-11]
 [-7.38285175e-06 -1.07772127e-06]
 [-7.64074886e-05 -1.11536814e-05]
 [-3.32464837e-04 -4.85319843e-05]
 [-6.08209855e-04 -8.87843125e-05]
 [-4.67796940e-04 -6.82889220e-05]
 [-1.51258103e-04 -2.20920426e-05]
 [-2.05197960e-05 -3.03149798e-06]
 [-1.11600332e-06 -2.08759469e-07]
 [ 3.58337051e-09 -2.39634062e-08]
 [ 6.86299276e-09 -4.49632200e-09]
 [-2.73008415e-04 -3.98527542e-05]
 [-2.82545120e-03 -4.12448874e-04]
 [-1.22941241e-02 -1.79465096e-03]
 [-2.24908057e-02 -3.28314080e-03]
 [-1.72982451e-02 -2.52541609e-03]
 [-5.59126583e-03 -8.18222542e-04]
 [-7.52555658e-04 -1.15989545e-04]
 

 This problem is unconstrained.



At iterate   10    f=  1.47334D+00    |proj g|=  6.46960D-03
Debug mode: Simulating MD run for phi=1.0471975511965974, psi=-1.0471975511965979

At iterate   20    f=  1.46485D+00    |proj g|=  5.60707D-04

           * * *

Tit   = total number of iterations
Tnf   = total number of function evaluations
Tnint = total number of segments explored during Cauchy searches
Skip  = number of BFGS updates skipped
Nact  = number of active bounds at final generalized Cauchy point
Projg = norm of the final projected gradient
F     = final function value

           * * *

   N    Tit     Tnf  Tnint  Skip  Nact     Projg        F
  100     28     31      1     0     0   8.948D-06   1.465D+00
  F =   1.4648453402821979     

CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL            
[[-0.90961859  0.81453703]
 [ 1.58901285  2.04339637]] [[ 1.04719755 -1.04719755]]
 -------------- BaysOpt loop, query 1 ---------------
[[-5.65795379e-08 -9.34756937e-09]
 [ 2.35763666e-06  2.15827448e-07]
 [ 1.55529

 This problem is unconstrained.


[[-0.90961859  0.81453703]
 [ 1.58901285  2.04339637]
 [ 1.04719755 -1.04719755]] [[-1.04719755 -1.74532925]]
 -------------- BaysOpt loop, query 2 ---------------
[[-1.74284969e-03 -1.99878976e-02]
 [-1.52031426e-02 -1.74389870e-01]
 [-5.56211648e-02 -6.39679947e-01]
 [-8.27192655e-02 -9.86185083e-01]
 [-2.69143378e-02 -6.36372708e-01]
 [ 9.06856646e-02 -1.62190558e-01]
 [ 1.61568857e-01 -1.17293457e-03]
 [ 1.05808894e-01  1.12366191e-02]
 [ 2.88661079e-02  3.30631521e-03]
 [ 3.30869690e-03  3.81026871e-04]
 [-6.40006643e-03 -7.33206028e-02]
 [-5.58251525e-02 -6.39705533e-01]
 [-2.03542355e-01 -2.34642679e+00]
 [-2.87283651e-01 -3.61568024e+00]
 [ 4.67965835e-02 -2.31758939e+00]
 [ 8.67964860e-01 -5.33278831e-01]
 [ 1.41844832e+00  9.08342457e-02]
 [ 9.23583970e-01  1.02907380e-01]
 [ 2.51859318e-01  2.89455559e-02]
 [ 2.88677633e-02  3.32521529e-03]
 [-1.01318962e-02 -1.13115345e-01]
 [-8.87470936e-02 -9.86960422e-01]
 [-3.22750995e-01 -3.62010173e+00]
 [-4.03270561e-01 -5.57226865e+

 This problem is unconstrained.
 This problem is unconstrained.


RUNNING THE L-BFGS-B CODE

           * * *

Machine precision = 2.220D-16
 N =          100     M =           10

At X0         0 variables are exactly at the bounds

At iterate    0    f=  3.04406D+01    |proj g|=  5.86190D-01

At iterate   10    f=  3.81042D+00    |proj g|=  1.46802D-02

At iterate   20    f=  3.73922D+00    |proj g|=  4.95248D-04

At iterate   30    f=  3.73919D+00    |proj g|=  1.42109D-05

           * * *

Tit   = total number of iterations
Tnf   = total number of function evaluations
Tnint = total number of segments explored during Cauchy searches
Skip  = number of BFGS updates skipped
Nact  = number of active bounds at final generalized Cauchy point
Projg = norm of the final projected gradient
F     = final function value

           * * *

   N    Tit     Tnf  Tnint  Skip  Nact     Projg        F
  100     32     36      1     0     0   7.372D-06   3.739D+00
  F =   3.7391895734651914     

CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL            
Debug mo

 This problem is unconstrained.
 This problem is unconstrained.



At iterate   30    f=  4.68210D+00    |proj g|=  1.65201D-05

           * * *

Tit   = total number of iterations
Tnf   = total number of function evaluations
Tnint = total number of segments explored during Cauchy searches
Skip  = number of BFGS updates skipped
Nact  = number of active bounds at final generalized Cauchy point
Projg = norm of the final projected gradient
F     = final function value

           * * *

   N    Tit     Tnf  Tnint  Skip  Nact     Projg        F
  100     31     34      1     0     0   9.770D-06   4.682D+00
  F =   4.6821047402747205     

CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL            
Debug mode: Simulating MD run for phi=-1.7453292519943295, psi=2.443460952792061
[[-0.90961859  0.81453703]
 [ 1.58901285  2.04339637]
 [ 1.04719755 -1.04719755]
 [-1.04719755 -1.74532925]
 [ 1.74532925  0.34906585]
 [-2.44346095 -0.34906585]] [[-1.74532925  2.44346095]]
 -------------- BaysOpt loop, query 5 ---------------
[[-2.64207161e-03 -2.38206316e-02]


 This problem is unconstrained.
 This problem is unconstrained.



At iterate   20    f=  5.38150D+00    |proj g|=  1.58069D-03

At iterate   30    f=  5.38143D+00    |proj g|=  1.47438D-05

           * * *

Tit   = total number of iterations
Tnf   = total number of function evaluations
Tnint = total number of segments explored during Cauchy searches
Skip  = number of BFGS updates skipped
Nact  = number of active bounds at final generalized Cauchy point
Projg = norm of the final projected gradient
F     = final function value

           * * *

   N    Tit     Tnf  Tnint  Skip  Nact     Projg        F
  100     31     35      1     0     0   6.573D-06   5.381D+00
  F =   5.3814284960281977     

CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL            
Debug mode: Simulating MD run for phi=0.34906585039886595, psi=1.7453292519943293
[[-0.90961859  0.81453703]
 [ 1.58901285  2.04339637]
 [ 1.04719755 -1.04719755]
 [-1.04719755 -1.74532925]
 [ 1.74532925  0.34906585]
 [-2.44346095 -0.34906585]
 [-1.74532925  2.44346095]
 [ 1.74532925 -2.44346095]] 

 This problem is unconstrained.
 This problem is unconstrained.


 [[-2.44346095 -2.44346095]]
 -------------- BaysOpt loop, query 9 ---------------
[[ 1.52162358e+00  3.00039800e+00]
 [ 2.30190803e+00  4.46277492e+00]
 [ 1.32910341e+00  2.29026248e+00]
 [ 1.14142266e-01 -3.07588268e-01]
 [-1.51587145e-01 -6.82431646e-01]
 [-2.39161295e-01 -6.01746227e-01]
 [-9.12063177e-01 -1.53388276e+00]
 [-1.53101776e+00 -2.34238512e+00]
 [-1.02853435e+00 -1.52097970e+00]
 [-2.84507444e-01 -4.14957651e-01]
 [ 2.31170582e+00  4.48731070e+00]
 [ 3.40331910e+00  6.31752730e+00]
 [ 1.62942761e+00  1.88850173e+00]
 [-3.68155775e-01 -2.87722464e+00]
 [-3.22962023e-01 -2.56114138e+00]
 [ 2.99083570e-01 -1.27342780e+00]
 [-3.34118241e-01 -2.32132963e+00]
 [-1.67120994e+00 -3.55559515e+00]
 [-1.39815445e+00 -2.32808964e+00]
 [-4.17092107e-01 -6.37481661e-01]
 [ 1.28883588e+00  2.03788061e+00]
 [ 1.75670391e+00  2.21799605e+00]
 [ 4.28377793e-01 -1.92017474e+00]
 [-4.03270548e-01 -5.57226865e+00]
 [ 1.10634888e+00 -3.70174747e+00]
 [ 3.38241378e+00 -1.05079840e+00]
 [ 3.89

      estimated_forces: [[[ 1.522e+00  3.000e+00]
                          [ 2.302e+00  4.463e+00]
                          ...
                          [-1.029e+00 -1.521e+00]
                          [-2.845e-01 -4.150e-01]]
                        
                         [[ 2.312e+00  4.487e+00]
                          [ 3.403e+00  6.318e+00]
                          ...
                          [-1.398e+00 -2.328e+00]
                          [-4.171e-01 -6.375e-01]]
                        
                         ...
                        
                         [[-7.557e-01  3.559e-04]
                          [-2.844e+00 -1.204e-04]
                          ...
                          [ 2.216e-02 -1.711e+00]
                          [-3.318e-02 -3.958e-01]]
                        
                         [[-4.823e-01  4.471e-03]
                          [-1.774e+00  1.630e-02]
                          ...
                          [-2.488e-02 -7.069e-01